---
- hosts: workstations
  tasks:

  - name: Copy arcgis earth
    win_copy:
      src: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ArcGIS\Earth
      dest: C:\Program Files
    become: yes
    become_user: root

  