---
- hosts: workstations
  tasks:

  #Create ansible temp directory
  - name: Create ansible playbook temp directory on target machine(s)
    win_file:
        path: C:\ProgramData\FPED\Discord-temp
        state: directory

  #Copy installation files to target machine
  - name: Copy installation files to target machine(s)
    win_copy:
        src: ~/iac-ansible/applications/DiscordSetup.exe
        dest: C:\ProgramData\FPED\Discord-temp\DiscordSetup.exe

  #Installation of Discord
  - name: Install Package - Discord
    win_package:
        path: C:\ProgramData\FPED\Discord-temp\DiscordSetup.exe
        state: present
        product_id:
#-----------------------------------------------------------------------

#Create ansible temp directory
  - name: Create ansible playbook temp directory on target machine(s)
    win_file:
        path: C:\ProgramData\FPED\ansible-temp
        state: directory

#Copy installation files to target machine
  - name: Copy installation files to target machine(s)
    win_copy:
        src: ~/iac-ansible/applications/VSCodeUserSetup-x64-1.57.1.exe
        dest: C:\ProgramData\FPED\ansible-temp\VSCodeUserSetup-x64-1.57.1.exe
    
  #Installation of MS Visual Studio Code
  - name: Install Package - Visual Studio Code 
    win_package:
        path: C:\ProgramData\FPED\ansible-temp\VSCodeUserSetup-x64-1.57.1.exe
        state: present
        product_id: auto

  