---
- hosts: windows
  #vars_prompt:
    #- name: username
      #prompt: Enter username
      #private: no

    #- name: password
      #prompt: Enter password
      #private: yes
      #encrypt: sha512_crypt
      #confirm: yes
      #salt_size: 7

  #ansible_user: "{{ username }}"
  #ansible_pass: "{{ password }}"

  tasks:

      - name: Ensure Chocolatey installed
        win_chocolatey:
          name: chocolatey
          state: present
