---
- hosts: windows
  become: yes
  become_user: root
  tasks:

  #Installation of VLC media Player
    - name: Ensure vlc 3.0.11 installed
      win_chocolatey:
        name: vlc
        state: present
        version: 3.0.11
        #source: http://internal/odata/repo
