---
- hosts: workstations
  #become: yes
  #become_user: root
  
  tasks:
  #Installation Notepad++ 
    - name: Ensure notepadplusplus 7.9 installed
      win_chocolatey:
        name: notepadplusplus
        state: present
        version: '7.9'
        ignore_checksums: yes #Had to add this in order to complete with version successfully