---
- hosts: windows
  become: yes
  become_user: root
  tasks:

#Installation of Java 8 update
#version: 8.262.10 was the only version they have
    - name: Ensure openjdk8jre x64 installed
      win_chocolatey:
        name: openjdk8jre
        state: present
        version: 8.262.10
        source: http://internal/odata/repo